apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobseeker-frontend
  name: jobseeker-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    name: jobseeker-frontend
  selector:
    app: jobseeker-frontend
    tier: frontend
  sessionAffinity: None