apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobseeker-frontend
  name: jobseeker-frontend
spec:
  ports:
  - name: http
    port: 8080
  - name: external
    port: 80
    targetPort: 8080
  selector:
    app: jobseeker-frontend
    tier: backend
  sessionAffinity: None
