apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobseeker-frontend
  name: jobseeker-frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
  - name: external
    port: 30034
    targetPort: 3000
  selector:
    app: jobseeker-frontend
    tier: backend
  sessionAffinity: None