apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobseeker-frontend
  name: jobseeker-frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    name: jobseeker-frontend
  selector:
    app: jobseeker-frontend
    tier: frontend
  sessionAffinity: None